services:
  app:
    ports:
      - 80:8080
    user: app:app
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: production
      args:
        - gid=1000
        - uid=1000
        - WORKDIR=/var/www/project-cgrd
    volumes:
      - .:/var/www/project-cgrd
    depends_on:
      - database

  database:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./.docker/db/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_USER:-root}
      MYSQL_USER: ${DB_USER:-project}
      MYSQL_PASSWORD: ${DB_PASSWORD:-project}
      MYSQL_DATABASE: ${DB_NAME:-project}
volumes:
    data:
