services:
  app:
    ports:
      - 80:8080
    user: app:app
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: dev
      args:
        - gid=1000
        - uid=1000
        - WORKDIR=/var/www/project-cgrd
    volumes:
      - .:/var/www/project-cgrd
    depends_on:
      - database

  database:
    image: mariadb:10.6
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_USER:-project}
      MARIADB_USER: ${DB_USER:-project}
      MARIADB_PASSWORD: ${DB_PASSWORD:-project}
      MARIADB_DATABASE: ${DB_NAME:-project}
volumes:
    data:
